name: Sync main branch from instructor branch

on:
  push:
    branches: [ instructors ]

jobs:
  sync-from-instructors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: python -m pip install --upgrade cogbooks
    - name: Build student versions
      run: |
        cogbooks -f notebooks/
        rm -r notebooks/*.md
        rm src/pbt_tutorial/basic_functions.py
        rm tests/test_fuzz.py
        rm tests/test_manual.py
        rm tests/test_metamorphic.py
        rm tests/test_parameterized.py
        rm tests/test_properties.py
    - name: Push to main branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add --force .
        git commit -m "Sync from instructors branch"
        git push --force origin HEAD:main
