name: Sync main branch from instructor branch

on:
  push:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: python -m pip install --upgrade cogbooks
    - name: Build student versions
      run: |
        echo cogbooks ...
    - name: Push to main branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add --force .
        git commit -m "Sync from instructor branch"
        echo git push --force origin HEAD:main
